# Generated by Django 5.2 on 2025-04-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('tecnica', models.TextField()),
                ('errores_comunes', models.TextField()),
                ('video_url', models.URLField(blank=True)),
            ],
        ),
    ]
